# Generated by Django 4.2.4 on 2023-08-14 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delightsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='price_per_unit',
        ),
    ]
