# Generated by Django 4.2.4 on 2023-08-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delightsapp', '0002_remove_ingredient_price_per_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
