# Generated by Django 4.2.4 on 2023-08-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delightsapp', '0003_alter_purchase_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='price_per_unit',
            field=models.FloatField(default=0),
        ),
    ]
