# Generated by Django 4.2.4 on 2023-08-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delightsapp', '0004_ingredient_price_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
