# Generated by Django 4.2.4 on 2023-08-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delightsapp', '0005_menuitem_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='menu_item_type',
            field=models.CharField(choices=[('DR', 'Drink'), ('BA', 'Bakery')], default='DRINK', max_length=2),
        ),
    ]
