# Generated by Django 4.2.4 on 2023-08-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delightsapp', '0006_menuitem_menu_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.TextField(default='Description', max_length=75),
        ),
    ]
